### PR TITLE
Clean up, 4.03 compat.

### PR DESCRIPTION
**Pull request by Drup**
Also, remove camlp4 dep and reindent.
I tagged 4.02 in repo.

### CODE REVIEW

**Comment by Drup** [comment]
Apparently, jenkins really don't like it.

**Comment by dannywillems** [comment]
Do you continue the 4.03.0 compatibility? @Drup

**Comment by Drup** [comment]
@dannywillems this is not compatible with 4.02, so if we merge that, we must move all the documentation generation to 4.03

**Comment by Drup** [comment]
(Or at least, fix the scripts to target the 4.02 tag)

**Comment by vasilisp** [comment]
We need this quite urgently. Ocsigen Start no longer compiles on 4.02. See ocsigen/ocsigen-start#413.

I think the best strategy is:

- Disable all doc generation by the 4.02 jobs
- Merge the PR
- Enable doc generation by the relevant 4.03 jobs. We will need to add a few missing 4.03 jobs (but the active projects should compile without trouble)

**Comment by vasilisp** [comment]
I merged this, and enabled doc generation with 4.03. Things seem to be working smoothly for now. Notify me if you notice any issues.

Unfortunately, it doesn't compile on 4.04. Given that `wikidoc` has little (no?) use outside our infrastructure, I will apply the default lazy strategy and defer a 4.04 version to the future.

**Pull request merged**
